# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='autor',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
