# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171218_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
